### ISSUE TITLE
Downloaded zip is detected as a virus threat by Windows 10 Security

### ISSUE THREAD

**Issue by Pixelsplasher** [undavide/Adobe-UXP#1]
False-positively detected as [Trojan:Script/Sabsik.TE.A!ml](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Sabsik.TE.A!ml&threatid=2147780197) by Windows Security

![image](https://user-images.githubusercontent.com/44748916/144952301-450a0560-9b61-43ad-a07e-0fec3eb0ea4c.png)

Windows version:

![image](https://user-images.githubusercontent.com/44748916/144952752-ba2ead1d-98aa-4eea-ae86-3e79bf874dc8.png)

**Comment by undavide** [comment]
Weird, thanks for letting me know! What is main.zip, the Adobe-UXP-main.zip from the full repo download?

**Comment by Pixelsplasher** [comment]
No problem, @undavide. **main.zip** is the short filename for the temp file used by Internet Download Manager for Adobe-UXP-main.zip.  I also tried downloading with Google Chrome only and without using IDM but Windows Security still detected it as a threat.

**Comment by undavide** [comment]
Thanks for testing, I'm gonna submit it for whitelisting.

**Comment by undavide** [comment]
Just submitted. It would be nice to know which file inside the ZIP the antivirus is specifically worried about, is this something you can dig? Thanks!

**Comment by Pixelsplasher** [comment]
Windows Security does not block the zip or extracted files anymore. Maybe it is already whitelisted.

**Comment by undavide** [comment]
Yep, they've whitelisted it :-) Maybe there was some node module it didn't like... ¯\\\_(ツ)_/¯
